MARGIN_TOP = 15
MARGIN_LEFT = 35

WINDOW_WIDTH = 1800
WINDOW_HEIGHT = 1000

LISTBOX_WIDTH = 550
LISTBOX_HEIGHT = 550
DISTANCE_BETWEEN_LISTBOXES = 60
LISTBOX_MARGIN_TOP = 50

MAPPING_LISTBOX_WIDTH = 1773
MAPPING_LISTBOX_HEIGHT = 300
MAPPING_LISTBOX_MARGIN_TOP = 50
MAPPING_LISTBOX_ITEMS_ON_TOP = 30

COLOR_ITEM_HAS_SELECTION = 'green'
COLOR_ITEM_MAPPED_CODE = 'blue'
COLOR_ITEM_EMPTY = 'white'

LABEL_WIDTH = 120
ENTRY_WIDTH = 200
BUTTON_WIDTH = 150
DROPDOWN_WIDTH = 210


EMPTY_CANDIDATES = {
    'text_similarity': [],
    'inverted_index': [],
    'word_embedding': [],
}
