WINDOW_WIDTH = 1800
WINDOW_HEIGHT = 1000

LISTBOX_WIDTH = 550
LISTBOX_HEIGHT = 600
DISTANCE_BETWEEN_LISTBOXES = 60
LISTBOX_DISTANCE_FROM_Y = 50

MAPPING_LISTBOX_WIDTH = 1700
MAPPING_LISTBOX_HEIGHT = 300

COLOR_ITEM_HAS_SELECTION = 'green'
COLOR_ITEM_MAPPED_CODE = 'blue'
COLOR_ITEM_EMPTY = 'white'
